spring:
    application:
        name: IslandSimulation
island:
    width: 100
    height: 20
app:
    refreshInterval: 5000
    initialAnimalsCount: 4
    animalMovementJobIntervalInSeconds: 5
    animalEatingJobIntervalInSeconds: 10
    plantAppearJobIntervalInSeconds: 10
    plantEatingJobIntervalInSeconds: 10
    animalBreedingJobIntervalInSeconds: 1
    populateIslandJobIntervalInMilliseconds: 500